export default function InfoPage({ infoPage, data, go }) {
  if (!data) {
    return null;
  }

  return (
    <div style={{ paddingBottom: 50 }}>
      <div style={{ background: data.color, borderRadius: 18, marginTop: 22, padding: "40px 38px", overflow: "hidden" }}>
        <button onClick={() => go("home")} style={{ background: "rgba(255,255,255,0.12)", border: "none", borderRadius: 7, padding: "5px 13px", color: "#fff", fontSize: 12, cursor: "pointer", fontWeight: 600, marginBottom: 18 }}>Back</button>
        <div><div style={{ fontSize: 42, marginBottom: 9 }}>{data.icon}</div><h1 style={{ margin: "0 0 9px", fontSize: 30, fontWeight: 900, color: "#fff" }}>{infoPage}</h1><p style={{ margin: 0, fontSize: 14, color: "rgba(255,255,255,0.75)", maxWidth: 520, lineHeight: 1.7 }}>{data.desc}</p></div>
      </div>
      {data.stats && <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14, marginTop: 20 }}>{data.stats.map((stat) => <div key={stat.l} style={{ background: "#fff", borderRadius: 14, padding: 20, textAlign: "center", border: "1px solid #f3f4f6" }}><p style={{ margin: "0 0 3px", fontSize: 26, fontWeight: 900, color: "#6366f1" }}>{stat.h}</p><p style={{ margin: 0, fontSize: 12, color: "#6b7280", fontWeight: 600 }}>{stat.l}</p></div>)}</div>}
      {data.jobs && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}>{data.jobs.map((job) => <div key={job} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 16px", borderRadius: 10, border: "1px solid #f3f4f6", marginBottom: 8, background: "#fafafa" }}><div><p style={{ margin: "0 0 2px", fontWeight: 700, fontSize: 14 }}>{job}</p><p style={{ margin: 0, fontSize: 11, color: "#6b7280" }}>Full-time · Remote/Bengaluru</p></div><button style={{ background: "linear-gradient(135deg,#6366f1,#8b5cf6)", color: "#fff", border: "none", borderRadius: 7, padding: "6px 14px", fontSize: 11, fontWeight: 700, cursor: "pointer" }}>Apply</button></div>)}</div>}
      {data.press && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}>{data.press.map((item) => <div key={item} style={{ display: "flex", justifyContent: "space-between", padding: "12px 0", borderBottom: "1px solid #f9fafb" }}><p style={{ margin: 0, fontWeight: 600, fontSize: 13 }}>{item}</p><span style={{ color: "#6366f1", fontWeight: 700, fontSize: 12, cursor: "pointer", marginLeft: 14 }}>Read</span></div>)}</div>}
      {data.posts && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>{data.posts.map((post) => <div key={post} style={{ background: "#f9fafb", borderRadius: 12, padding: 16, border: "1px solid #f3f4f6" }}><span style={{ background: "#ede9fe", color: "#6366f1", fontSize: 10, fontWeight: 700, padding: "2px 7px", borderRadius: 9 }}>Article</span><p style={{ margin: "8px 0 0", fontWeight: 700, fontSize: 13, color: "#111827", lineHeight: 1.4 }}>{post}</p></div>)}</div></div>}
      {data.contacts && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>{data.contacts.map((contact) => <div key={contact.l} style={{ background: "#f9fafb", borderRadius: 12, padding: 16, border: "1px solid #f3f4f6" }}><span style={{ fontSize: 26 }}>{contact.icon}</span><p style={{ margin: "7px 0 3px", fontWeight: 700, fontSize: 13 }}>{contact.l}</p><p style={{ margin: 0, fontSize: 12, color: "#6366f1", fontWeight: 600 }}>{contact.v}</p></div>)}</div></div>}
      {data.faqs && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}>{data.faqs.map((faq) => <div key={faq.q} style={{ border: "1px solid #f3f4f6", borderRadius: 10, marginBottom: 8, overflow: "hidden" }}><div style={{ padding: "12px 16px", background: "#fafafa" }}><span style={{ fontSize: 13, fontWeight: 700 }}>{faq.q}</span></div><div style={{ padding: "10px 16px", background: "#fff", borderTop: "1px solid #f3f4f6" }}><p style={{ margin: 0, fontSize: 13, color: "#374151", lineHeight: 1.7 }}>{faq.a}</p></div></div>)}</div>}
      {data.steps && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}><div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 12 }}>{data.steps.map((step, index) => <div key={step} style={{ textAlign: "center", padding: "18px 12px", background: "#f9fafb", borderRadius: 12 }}><div style={{ width: 34, height: 34, borderRadius: "50%", background: "linear-gradient(135deg,#6366f1,#8b5cf6)", color: "#fff", fontWeight: 900, fontSize: 15, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 10px" }}>{index + 1}</div><p style={{ margin: 0, fontSize: 12, fontWeight: 600, color: "#374151" }}>{step}</p></div>)}</div></div>}
      {data.delivery && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>{data.delivery.map((option) => <div key={option.t} style={{ background: "#f9fafb", borderRadius: 12, padding: 16, border: "1px solid #f3f4f6" }}><p style={{ margin: "0 0 3px", fontWeight: 800, fontSize: 14 }}>{option.t}</p><p style={{ margin: "0 0 2px", fontSize: 12, color: "#6366f1", fontWeight: 700 }}>{option.time}</p><p style={{ margin: 0, fontSize: 11, color: "#6b7280" }}>{option.cost}</p></div>)}</div></div>}
      {data.sections && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}>{data.sections.map((section, index) => <div key={section} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 0", borderBottom: "1px solid #f9fafb" }}><span style={{ width: 26, height: 26, borderRadius: 7, background: "#ede9fe", color: "#6366f1", fontWeight: 800, fontSize: 12, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{index + 1}</span><p style={{ margin: 0, fontSize: 13, fontWeight: 600, color: "#374151" }}>{section}</p></div>)}</div>}
      {data.cookies && <div style={{ background: "#fff", borderRadius: 16, padding: 22, marginTop: 18, border: "1px solid #f3f4f6" }}>{data.cookies.map((cookie) => <div key={cookie.t} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 0", borderBottom: "1px solid #f9fafb" }}><p style={{ margin: 0, fontWeight: 600, fontSize: 13 }}>{cookie.t}</p><span style={{ background: cookie.r ? "#fee2e2" : "#d1fae5", color: cookie.r ? "#991b1b" : "#065f46", padding: "3px 10px", borderRadius: 18, fontSize: 10, fontWeight: 700 }}>{cookie.r ? "Required" : "Optional"}</span></div>)}</div>}
    </div>
  );
}
