import { ADMIN_EMAIL, CATS, ORDERS_DATA, PRODUCTS, SC } from "../../data/storeData";

export default function AdminPanel({ adminTab, setAdminTab, onExitAdmin, onLogout }) {
  return (
    <div style={{ display: "flex", minHeight: "100vh", fontFamily: "system-ui,sans-serif", background: "#f9fafb" }}>
      <aside style={{ width: 210, background: "#1e1b4b", display: "flex", flexDirection: "column", flexShrink: 0 }}>
        <div style={{ padding: "18px 14px", borderBottom: "1px solid rgba(255,255,255,0.08)", display: "flex", alignItems: "center", gap: 9 }}><div style={{ width: 32, height: 32, borderRadius: 9, background: "linear-gradient(135deg,#6366f1,#8b5cf6)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>🚀</div><span style={{ fontSize: 16, fontWeight: 900, color: "#fff" }}>Shipmora</span></div>
        <nav style={{ flex: 1, padding: "8px 6px" }}>
          {[{ id: "dashboard", icon: "📊", label: "Dashboard" }, { id: "products", icon: "📦", label: "Products" }, { id: "orders", icon: "🛒", label: "Orders" }, { id: "customers", icon: "👥", label: "Customers" }, { id: "marketing", icon: "📣", label: "Marketing" }, { id: "analytics", icon: "📈", label: "Analytics" }, { id: "settings", icon: "⚙️", label: "Settings" }].map((item) => <button key={item.id} onClick={() => setAdminTab(item.id)} style={{ display: "flex", alignItems: "center", gap: 10, width: "100%", padding: "10px 12px", borderRadius: 9, border: "none", cursor: "pointer", background: adminTab === item.id ? "rgba(99,102,241,0.2)" : "transparent", color: adminTab === item.id ? "#a5b4fc" : "#7c85a2", fontWeight: adminTab === item.id ? 700 : 500, fontSize: 14, marginBottom: 2, textAlign: "left" }}><span style={{ fontSize: 17 }}>{item.icon}</span>{item.label}</button>)}
        </nav>
        <div style={{ padding: "10px 6px", borderTop: "1px solid rgba(255,255,255,0.08)" }}><button onClick={onExitAdmin} style={{ display: "flex", alignItems: "center", gap: 10, width: "100%", padding: "9px 12px", borderRadius: 9, border: "none", cursor: "pointer", background: "rgba(239,68,68,0.15)", color: "#fca5a5", fontWeight: 700, fontSize: 14 }}><span style={{ fontSize: 17 }}>🏪</span>View Store</button></div>
      </aside>
      <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
        <header style={{ background: "#fff", borderBottom: "1px solid #e5e7eb", padding: "0 24px", height: 60, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <h2 style={{ margin: 0, fontSize: 17, fontWeight: 800, color: "#111827", textTransform: "capitalize" }}>{adminTab}</h2>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ width: 34, height: 34, borderRadius: "50%", background: "linear-gradient(135deg,#6366f1,#8b5cf6)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 800, fontSize: 13 }}>A</div><div><p style={{ margin: 0, fontSize: 12, fontWeight: 700 }}>Admin</p><p style={{ margin: 0, fontSize: 11, color: "#9ca3af" }}>{ADMIN_EMAIL}</p></div><button onClick={onLogout} style={{ background: "#fee2e2", color: "#ef4444", border: "none", borderRadius: 8, padding: "6px 12px", fontSize: 12, cursor: "pointer", fontWeight: 700 }}>Logout</button></div>
        </header>
        <main style={{ flex: 1, overflowY: "auto", padding: 24 }}>
          {adminTab === "dashboard" && <div><h1 style={{ margin: "0 0 20px", fontSize: 22, fontWeight: 900 }}>Dashboard</h1><div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 16, marginBottom: 24 }}>{[{ l: "Revenue", v: "₹18,42,390", ch: "+23%", ic: "💰", up: true }, { l: "Orders Today", v: "1,284", ch: "+12%", ic: "📦", up: true }, { l: "Customers", v: "48,291", ch: "+8%", ic: "👥", up: true }, { l: "Refunds", v: "34", ch: "-5%", ic: "↩️", up: false }].map((stat) => <div key={stat.l} style={{ background: "#fff", borderRadius: 14, padding: "18px 20px", border: "1px solid #f3f4f6" }}><p style={{ margin: "0 0 6px", fontSize: 12, color: "#6b7280", fontWeight: 600 }}>{stat.l}</p><p style={{ margin: "0 0 6px", fontSize: 22, fontWeight: 900, color: "#111827" }}>{stat.v}</p><span style={{ fontSize: 11, fontWeight: 700, color: stat.up ? "#10b981" : "#ef4444" }}>{stat.up ? "↑" : "↓"} {stat.ch}</span></div>)}</div><div style={{ background: "#fff", borderRadius: 14, padding: 20, border: "1px solid #f3f4f6" }}><h3 style={{ margin: "0 0 16px", fontWeight: 800, fontSize: 15 }}>Recent Orders</h3><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr>{["Order", "Customer", "Product", "Amount", "Status", "Date"].map((heading) => <th key={heading} style={{ textAlign: "left", padding: "7px 10px", fontSize: 11, color: "#9ca3af", fontWeight: 700, borderBottom: "1px solid #f3f4f6" }}>{heading}</th>)}</tr></thead><tbody>{ORDERS_DATA.map((order) => <tr key={order.id}><td style={{ padding: "11px 10px", fontSize: 12, fontWeight: 700, color: "#6366f1" }}>{order.id}</td><td style={{ padding: "11px 10px", fontSize: 12 }}>{order.customer}</td><td style={{ padding: "11px 10px", fontSize: 12 }}>{order.product}</td><td style={{ padding: "11px 10px", fontSize: 12, fontWeight: 700 }}>{order.amount}</td><td style={{ padding: "11px 10px" }}><span style={{ padding: "3px 9px", borderRadius: 20, fontSize: 11, fontWeight: 700, background: SC[order.status]?.bg, color: SC[order.status]?.c }}>{order.status}</span></td><td style={{ padding: "11px 10px", fontSize: 12, color: "#6b7280" }}>{order.date}</td></tr>)}</tbody></table></div></div>}
          {adminTab === "products" && <div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}><h1 style={{ margin: 0, fontSize: 22, fontWeight: 900 }}>Products</h1><button style={{ background: "linear-gradient(135deg,#6366f1,#8b5cf6)", color: "#fff", border: "none", borderRadius: 9, padding: "9px 18px", fontWeight: 700, cursor: "pointer", fontSize: 13 }}>+ Add Product</button></div><div style={{ background: "#fff", borderRadius: 14, border: "1px solid #f3f4f6", overflow: "hidden" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr style={{ background: "#f9fafb" }}>{["Product", "Category", "Price", "Rating", "Actions"].map((heading) => <th key={heading} style={{ textAlign: "left", padding: "10px 14px", fontSize: 11, color: "#6b7280", fontWeight: 700 }}>{heading}</th>)}</tr></thead><tbody>{PRODUCTS.map((product) => <tr key={product.id}><td style={{ padding: "12px 14px" }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ width: 38, height: 38, borderRadius: 9, background: `${product.color}22`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 }}>{product.emoji}</div><p style={{ margin: 0, fontSize: 13, fontWeight: 700 }}>{product.name}</p></div></td><td style={{ padding: "12px 14px", fontSize: 12 }}>{CATS.find((cat) => cat.id === product.cat)?.label}</td><td style={{ padding: "12px 14px", fontSize: 13, fontWeight: 800 }}>₹{product.price.toLocaleString()}</td><td style={{ padding: "12px 14px", fontSize: 12, color: "#f59e0b" }}>★ {product.rating}</td><td style={{ padding: "12px 14px" }}><div style={{ display: "flex", gap: 6 }}><button style={{ background: "#ede9fe", color: "#6366f1", border: "none", borderRadius: 7, padding: "5px 10px", fontSize: 12, cursor: "pointer", fontWeight: 600 }}>Edit</button><button style={{ background: "#fee2e2", color: "#ef4444", border: "none", borderRadius: 7, padding: "5px 10px", fontSize: 12, cursor: "pointer", fontWeight: 600 }}>Delete</button></div></td></tr>)}</tbody></table></div></div>}
          {adminTab === "orders" && <div><h1 style={{ margin: "0 0 20px", fontSize: 22, fontWeight: 900 }}>Orders</h1><div style={{ background: "#fff", borderRadius: 14, padding: 20, border: "1px solid #f3f4f6" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr style={{ background: "#f9fafb" }}>{["Order", "Customer", "Product", "Amount", "Status", "Date"].map((heading) => <th key={heading} style={{ textAlign: "left", padding: "9px 12px", fontSize: 11, color: "#6b7280", fontWeight: 700 }}>{heading}</th>)}</tr></thead><tbody>{ORDERS_DATA.map((order) => <tr key={order.id}><td style={{ padding: 12, fontSize: 12, fontWeight: 700, color: "#6366f1" }}>{order.id}</td><td style={{ padding: 12, fontSize: 12 }}>{order.customer}</td><td style={{ padding: 12, fontSize: 12 }}>{order.product}</td><td style={{ padding: 12, fontSize: 12, fontWeight: 800 }}>{order.amount}</td><td style={{ padding: 12 }}><span style={{ padding: "3px 9px", borderRadius: 20, fontSize: 11, fontWeight: 700, background: SC[order.status]?.bg, color: SC[order.status]?.c }}>{order.status}</span></td><td style={{ padding: 12, fontSize: 12, color: "#6b7280" }}>{order.date}</td></tr>)}</tbody></table></div></div>}
          {["customers", "marketing", "analytics", "settings"].includes(adminTab) && <div><h1 style={{ margin: "0 0 18px", fontSize: 22, fontWeight: 900, textTransform: "capitalize" }}>{adminTab}</h1><div style={{ background: "#fff", borderRadius: 14, padding: 40, border: "1px solid #f3f4f6", textAlign: "center", color: "#9ca3af" }}><div style={{ fontSize: 60, marginBottom: 14 }}>🚧</div><p style={{ fontSize: 17, fontWeight: 600, color: "#374151" }}>Coming Soon</p></div></div>}
        </main>
      </div>
    </div>
  );
}
